### ISSUE TITLE
Tikrai laukiu jūsų atsakymo!

### ISSUE THREAD

**Issue by VaiperIPTV** [augustas2/iptv#1]
Sveiki, aš tikrai norėčiau sužinoti apie jūsų įkeliamą IPTV grojaraštį.
(Atsiprašau, kad parašiau čia, nes nėra pranešimų)
Grojaraščio failas udp nuoroda. Ar jis veiks tik Lietuvoje, ar yra „Penki“ tiekėjas?

**Comment by augustas2** [comment]
Sveikas. Šis grojaroštis veikia tik Lietuvoje su “Penki” tiekėju. Su jokiu kitu neveiks.

**Comment by VaiperIPTV** [comment]
Ačiū už atsakymą
