### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by andiukas** [augustas2/iptv#2]
Sveikas, po kanalų adresų pakeitimo problemos su EPG. Pvz TV3 HD rusiško kanalo EPG :(

**Comment by augustas2** [comment]
Kokia programą naudoji? Jeigu Kodi, tada reik išvalyt cache.
Kaip tai padaryt ant Kodi: https://www.youtube.com/watch?v=7az6BO9-2FY

**Comment by andiukas** [comment]
Dėkui, padėjo ;)
