### ISSUE TITLE
kanalus atnaujinti

### ISSUE THREAD

**Issue by karkaaa** [augustas2/iptv#5]
Sveikas,

Pasikeite kanalu adresai. Gal kada turesi laiko sutvarkyti?

Aciu :)

**Comment by augustas2** [comment]
Sveikas,

Galėsiu sutvarkyti tik penktadienį arba šeštadienį. Būtu šaunu jei paminėtum kurie kanalai neveikia, nes užtruksiu eidamas ir tikrindamas 😉

**Comment by karkaaa** [comment]
Kiek ziurejau tai ten reik tikrinti visus nes kurie dar rodo bet jau kitas
kanalas..

**Comment by augustas2** [comment]
Kanalų sąrašas atnaujintas. Liko tik veikiantys kanalai.

**Comment by arunasaras** [comment]
visi august2 kanalai nustojo veikti. gal surasi laiko is naujo praskanuoti.prasytume
