### ISSUE TITLE
Neveikia!

### ISSUE THREAD

**Issue by MrVinyla** [augustas2/iptv#6]
Sveiki,
Jau beveik trečią diena neveikia IPTV, 8-tą lapkričio diena veikė LRT HD ir TV 3 HD o patikrinus kitus atsitiktinius gal kokius 10 vnt. nei vienas nepasileido. Visų ~180 aišku netikrinau. Turbūt keitėsi aipyšnikai? Galima patvarkyti? Ačiū už Jūsų darbą.

**Comment by augustas2** [comment]
Kaip ir kitoje temoje rašiau, deja panašu kad nebegalėsime mėgautis šiuo gėriu nes Penki sudėjo apsaugas.
