### ISSUE TITLE
Ar pakeite Penki vel adresasija

### ISSUE THREAD

**Issue by varijot** [augustas2/iptv#7]
Sveiki,
Nežinote skynet'as vel pakeitė adresus ar išvis kranelį užsuko? Vakar bent tai nerodė šiandien dar neturėjau galimybės pasižiūrėti.

**Comment by arunasaras** [comment]
is pradziu dingo dalis. Bet rodo visi HD ir lietuviski. pries geras 4 dienas dingo visi. gal kas galit imesti atnaujinta.

**Comment by arunasaras** [comment]
gal augustas2 galetu is naujo praskanuoti.butume dekingi

**Comment by augustas2** [comment]
Kad nelabai ką praskanuosi, nes panašu Penki užsuko kranelį :(

**Comment by arunasaras** [comment]
gaila. tai nėra išeities? Tas palylistas buvo tikras gėris

**Comment by Navigate** [comment]
Ar galėtum į EPG įdėti TV3 sport, TV3 sport2, TV3 film. TV24 jau duoda programą.

**Comment by arunasaras** [comment]
Augustai, jau vel veikia Skynet. Visu netikrinau. Bet visi LT HD veikia, o ne HD neveikia

**Comment by varijot** [comment]
Ar tikrai nes pas mane nieks neveikia.

**Comment by augustas2** [comment]
EPG atnaujintas. Dabar yra visi TV3 grupės kanalai. Panašu, kad šio projekto esmė liks tik EPG skirtas lietuvos rinkai. Ateity ketinu atnaujinti informaciją prie projekto.
